#!/usr/bin/env python3
"""data/cellar.json -> CELLAR.md

Do not edit CELLAR.md by hand. Change the JSON and run this script.
"""
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cellar import (LABEL, ROOT, STATUS, load, qty, regions, status, usd,
                    value, vintage)

OUT = ROOT / "CELLAR.md"


def label(b):
    s = b.get("display") or f"{b['producer']} {b['wine']}"
    if b.get("format_ml", 750) != 750:
        s += f" ({b['format_ml']}ml)"
    if qty(b) > 1:
        s += f" x{qty(b)}"
    return s


def table(rows, header):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def main():
    d = load()
    bs = sorted(d["bottles"], key=lambda b: b["id"])
    total = sum(qty(b) for b in bs)
    worth = sum(value(b) for b in bs)
    groups, order = regions(bs)

    L = [
        "<!-- Generated by scripts/build_cellar.py from data/cellar.json. Do not edit. -->",
        "",
        "# Cellar",
        "",
        f"As of {d['updated']} · {total} bottles / {len(bs)} labels · est. {usd(worth)} · "
        f"stored at {d['storage']['temp_c']}°C",
        "",
        "## By region",
        "",
        table([[groups[s]["name"], str(groups[s]["n"]), usd(groups[s]["v"])] for s in order],
              ["Region", "Bottles", "Value"]),
        "",
    ]

    for key, title, _ in STATUS:
        sel = [b for b in bs if status(b) == key]
        if not sel:
            continue
        L += [
            "",
            f"## {title} ({sum(qty(b) for b in sel)})",
            "",
            table([[str(b["id"]), label(b), str(vintage(b)),
                    f"{b['drink_from']}-{b['drink_to']}", b["short"]] for b in sel],
                  ["#", "Wine", "Vintage", "Window", "Note"]),
        ]

    L += ["", "---", "", "## All bottles", ""]
    L.append(table(
        [[str(b["id"]), str(vintage(b)), label(b), b["region"], LABEL[status(b)],
          f"{b['drink_from']}-{b['drink_to']}", usd(value(b))] for b in bs],
        ["#", "Vintage", "Wine", "Region", "Status", "Window", "Value"]))

    L += [
        "",
        "> Status is derived from the drinking window, not stored: past the window is post "
        "peak; two years or less left is urgent; not yet open is hold; a quarter of the way "
        "in — or five years past the opening — is peak; everything else is drink now.",
        "",
        f"> {d['storage']['note']}",
        "",
    ]

    OUT.write_text("\n".join(L) + "\n")
    print(f"{OUT.name}: {total} bottles / {len(bs)} labels")


if __name__ == "__main__":
    main()
