#!/usr/bin/env python3
"""data/cellar.json -> PRICES.md

A checklist of the bottles whose price is not yet confirmed against a
Wine-Searcher page, ordered by how much each one moves the cellar total.
Do not edit PRICES.md by hand.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cellar import ROOT, held, load, qty, usd, value, vintage

OUT = ROOT / "PRICES.md"
TIER = {"verified": "confirmed", "estimate": "estimated", "unverified": "unverified"}


def main():
    d = load()
    bs = sorted(held(d["wines"]), key=lambda b: b["id"])
    todo = [b for b in bs if b["price"]["confidence"] != "verified"]
    todo.sort(key=value, reverse=True)

    rows = []
    for i, b in enumerate(todo, 1):
        rows.append("| " + " | ".join([
            str(i), f'{b["id"]:02d}', b["display"], str(vintage(b)),
            usd(b["price"]["avg_usd"]), TIER[b["price"]["confidence"]],
            f'[open]({b["ws_url"]})',
        ]) + " |")

    done = [b for b in bs if b["price"]["confidence"] == "verified"]
    L = [
        "<!-- Generated by scripts/build_prices.py from data/cellar.json. Do not edit. -->",
        "",
        "# Price checklist",
        "",
        "Wine-Searcher blocks automated access, so these averages cannot be fetched. Open a "
        "link, read the **Avg Price**, and the value goes into `data/cellar.json`.",
        "",
        "> If the page's location filter is set to a country, you are reading that country's "
        "average. Leave it on All for the worldwide average.",
        "",
        f"{len(todo)} of {len(bs)} labels still need confirming, ordered by how much each one "
        "moves the cellar total.",
        "",
        "| | # | Wine | Vintage | Recorded | Basis | Link |",
        "|---|---|---|---|---|---|---|",
        *rows,
        "",
    ]
    if done:
        L += [
            "## Confirmed",
            "",
            "| # | Wine | Vintage | Avg price |",
            "|---|---|---|---|",
            *[f'| {b["id"]:02d} | {b["display"]} | {vintage(b)} | '
              f'{usd(b["price"]["avg_usd"])} |' for b in done],
            "",
        ]
    L += [
        "With a Wine-Searcher API key the whole list resolves in one pass:",
        "",
        "```",
        "WS_API_KEY=... python3 scripts/fetch_ws_prices.py",
        "```",
        "",
    ]
    OUT.write_text("\n".join(L))
    print(f"{OUT.name}: {len(todo)} to confirm / {len(bs)} labels")


if __name__ == "__main__":
    main()
